### ISSUE TITLE
crosscat needs check.sh

### ISSUE THREAD

**Issue by riastradh-probcomp** [mit-probabilistic-computing-project/crosscat#36]
Should take a single shell command to build Crosscat and run all automatic tests.

**Comment by riastradh-probcomp** [comment]
Secondary issue: the automatic tests are hopelessly bad and do almost nothing to ensure that what Crosscat computes is reasonable.

**Comment by gregory-marton** [comment]
So far what we have are python tests that segfault, and C++ tests that e.g. don't check for memory leaks, and integration testing via bayeslite. If the python tests worked, it would be easy enough to write a python test to check that the C++ tests passed, which would make it a single command.  Thanks for updating the README.rst to reflect how to run the C++ tests!

**Comment by riastradh-probcomp** [comment]
Fixed in c14344e1343210ddfbd71cb38f27e1c44b6a72ee.
